### ISSUE TITLE
Hardware SPI support

### ISSUE THREAD

**Issue by riklaunim** [adafruit/Adafruit_SHARP_Memory_Display#13]
Adafruit_SSD1325 has the option to use hardware SPI while this library doesn't - which prevents from using a memory LCD with other SPI devices on the microcontroller SPI pins. Looking at pull requests it looks like other where trying to add that ( https://github.com/adafruit/Adafruit_SHARP_Memory_Display/pull/6 ) but it wasn't merged.

**Comment by ladyada** [comment]
refactored and fixed SPI - we now use busio.
